import localFont from "next/font/local";
import "./globals.css";

import { Fugaz_One } from "next/font/google";

const fugaz = Fugaz_One({ subsets: ["latin"], weight: ["400"] });

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "New App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`px-2 max-w-screen-2xl mx-auto text-sm sm:text-base min-h-screen flex flex-col bg-gray-100  ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        {/* {footer} */}
      </body>
    </html>
  );
}
